apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: application-updated
  namespace: events
spec:
  template:
    serviceAccountName: operate-workflow-sa
  resource:
    applicationdeployed:
      eventTypes:
        - UPDATE
      group: argoproj.io
      namespace: "devops-tools"
      resource: applications
      version: v1alpha1
      filter:
        afterStart: true
        fields:
          - key: status.health.status
            operation: "=="
            value: Healthy
        labels:
          - key: generated
            operation: "=="
            value: "true"
    applicationcreated:
      eventTypes:
        - ADD
      group: argoproj.io
      namespace: "devops-tools"
      resource: applications
      version: v1alpha1
      filter:
        afterStart: true
        labels:
          - key: generated
            operation: "=="
            value: "true"
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: application-deployed
  namespace: events
spec:
  dependencies:
    - name: application-deployed
      eventSourceName: application-updated
      eventName: applicationdeployed
    - name: application-created
      eventSourceName: application-updated
      eventName: applicationcreated
  template:
    serviceAccountName: operate-workflow-sa
  triggers:
    - template:
        conditions: "application-deployed && application-created"
        name: templated-workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: executing-integrationtests-
                namespace: builds
              spec:
                serviceAccountName: operate-workflow-sa
                entrypoint: integration-test
                arguments:
                  parameters:
                  - name: application
                    value: "gets set from playload"
                templates:
                  - name: integration-test
                    dag:
                      tasks:
                        - name: checkout-code
                          template: checkout-code
                        - name: wait-for-deployment
                          template: wait-for-deployment
                        - name: executing-integration-test
                          template: executing-integration-test
                          depends: "checkout-code && wait-for-deployment"
                  - name: checkout-code
                    container:
                      image: docker/whalesay:latest
                      command: [cowsay]
                      args: ["dummy checkout code"]
                  - name: wait-for-deployment
                    container:
                      image: docker/whalesay:latest
                      command: [ cowsay ]
                      args: [ "waiting for deployment of application" ]
                  - name: executing-integration-test
                    container:
                      image: docker/whalesay:latest
                      command: [ cowsay ]
                      args: [ "executing integration tests" ]
---