apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: containerimage-operations
spec:
  workflowMetadata:
    labels:
      app: argo
      clusterworkflowtemplate: containerimage-operations
  templates:
    - name: build-and-push-image
      metadata:
        labels:
          template: build-and-push-image
      inputs:
        parameters:
          - name: registry
          - name: repository
          - name: containerfile
          - name: suffix
            default: ""
      securityContext:
        fsGroup: 0
      container:
        name: buildah
        image: ghcr.io/gepaplexx/buildah:latest
        command:
          - "/bin/bash"
          - "-c"
        args:
          - >-
            buildah bud
            --build-arg=BRANCH={{ workflow.parameters.environment }}
            --build-arg=COMMIT={{ workflow.parameters.commit-hash }}
            --build-arg=VERSION={{ workflow.parameters.commit-hash }}
            --build-arg=TIMESTAMP=$(date +%Y-%M-%dT%H:%M:%S)
            --ulimit nofile=1048576:1048576
            -f {{ inputs.parameters.containerfile }} 
            -t {{ inputs.parameters.registry }}/{{ inputs.parameters.repository }}/{{ workflow.parameters.reponame }}:{{ workflow.parameters.commit-hash }}{{ inputs.parameters.suffix }} 
            /mnt/out/{{ workflow.parameters.reponame }} &&
            buildah push  --authfile /home/build/.docker/config.json
            {{ inputs.parameters.registry }}/{{ inputs.parameters.repository }}/{{ workflow.parameters.reponame }}:{{ workflow.parameters.commit-hash }}{{ inputs.parameters.suffix }}
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: true
          capabilities:
            add:
              - CHOWN
              - DAC_OVERRIDE
              - SETGID
              - SETUID
        volumeMounts:
          - name: workspace
            mountPath: /mnt/out/
          - name: pipeline-secrets
            mountPath: /home/build/.docker/config.json
            subPath: config.json
            mode: 0400

    - name: scan-container-image-trivy
      metadata:
        labels:
          template: scan-container-image-trivy
      inputs:
        parameters:
          - name: report-severity
          - name: registry
          - name: repository
      initContainers:
        - name: prerequisites
          image: alpine:latest
          command:
            - "sh"
          args:
            - "-c"
            - "mkdir -p /mnt/out/{{ workflow.parameters.reponame }}/{{ workflow.parameters.commit-hash }}/"
          volumeMounts:
            - mountPath: /mnt/out/
              name: workspace
          securityContext:
            runAsUser: 1000
      container:
        name: trivy
        image: docker.io/aquasec/trivy:latest
        command:
          - "trivy"
        args:
          - "image"
          - "--severity={{ inputs.parameters.report-severity }}"
          - "--format=template"
          - "--template=@contrib/html.tpl"
          - "--cache-dir=/tmp/trivy/cache/"
          - "--ignore-unfixed"
          - "--output=/mnt/out/{{ workflow.parameters.reponame }}/{{ workflow.parameters.commit-hash }}/trivy.html"
          - "{{ inputs.parameters.registry }}/{{ inputs.parameters.repository }}/{{ workflow.parameters.reponame }}:{{ workflow.parameters.commit-hash }}-to-scan"
        volumeMounts:
          - name: cache
            mountPath: /tmp/trivy/cache
            subPath: cache
          - name: workspace
            mountPath: /mnt/out/

    - name: container-security-error-build-trivy
      metadata:
        labels:
          template: scan-container-image
      inputs:
        parameters:
          - name: registry
          - name: repository
          - name: severity
      container:
        name: trivy
        image: docker.io/aquasec/trivy:latest
        command:
          - "trivy"
        args:
          - "image"
          - "--severity={{ inputs.parameters.severity }}"
          - "--ignore-unfixed"
          - "--cache-dir=/tmp/trivy/cache/"
          - "--exit-code=1"
          - "{{ inputs.parameters.registry }}/{{ inputs.parameters.repository }}/{{ workflow.parameters.reponame }}:{{ workflow.parameters.commit-hash }}-to-scan"
        volumeMounts:
          - name: cache
            mountPath: /tmp/trivy/cache
            subPath: cache

    - name: retag-container-image
      metadata:
        labels:
          template: retag-container-image
      inputs:
        parameters:
          - name: old-tag
          - name: new-tag
          - name: registry
          - name: repository
      container:
        image: quay.io/containers/skopeo:latest
        command:
          - skopeo
        args:
          - "copy"
          - "--authfile=/config.json"
          - "docker://{{ inputs.parameters.registry }}/{{ inputs.parameters.repository }}/{{ workflow.parameters.reponame }}:{{ inputs.parameters.old-tag }}"
          - "docker://{{ inputs.parameters.registry }}/{{ inputs.parameters.repository }}/{{ workflow.parameters.reponame }}:{{ inputs.parameters.new-tag }}"
        volumeMounts:
          - name: pipeline-secrets
            mountPath: /config.json
            subPath: config.json
