apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-diamond-
  namespace: builds
spec:
  entrypoint: diamond
  serviceAccountName: operate-workflow-sa
  templates:
    - name: echo
      inputs:
        parameters:
          - name: message
      container:
        image: alpine:3.7
        command: [echo, "{{inputs.parameters.message}}"]
    - name: diamond
      dag:
        tasks:
          - name: A
            template: echo
            arguments:
              parameters: [{name: message, value: A}]
          - name: D
            depends: "B && C"
            template: echo
            arguments:
              parameters: [{name: message, value: D}]
          - name: B
            depends: "A"
            template: echo
            arguments:
              parameters: [{name: message, value: B}]
          - name: C
            depends: "A"
            template: echo
            arguments:
              parameters: [{name: message, value: C}]
          - name: Recover
            depends: "B.Failed || C.Failed || D.Failed"
            template: echo
            arguments:
              parameters: [{name: message, value: Recover}]
